name: PULSE
description: "A community engagement mobile application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  http: ^1.1.0
  dropdown_search: ^5.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  firebase_database: ^10.4.6
  firebase_storage: ^11.6.6
  path: ^1.8.0
  flutter_web_plugins:
    sdk: flutter
  photo_view: ^0.14.0
  mailer: ^6.0.1
  pin_code_fields: ^8.0.1
  crypto: ^3.0.3
  cloud_functions: ^4.7.6
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  macos: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/icon/
  uses-material-design: true
