name: PULSE
description: "A community engagement mobile application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  http: ^1.1.0
  dropdown_search: ^5.0.6
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_database: ^11.2.0
  firebase_storage: ^12.3.7
  path: ^1.8.0
  flutter_web_plugins:
    sdk: flutter
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  macos: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/icon/
  uses-material-design: true
